[2023-05-05T02:06:15.072+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_market_pipeline_v0.data_processing manual__2023-05-05T02:06:13.650215+00:00 [queued]>
[2023-05-05T02:06:15.077+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_market_pipeline_v0.data_processing manual__2023-05-05T02:06:13.650215+00:00 [queued]>
[2023-05-05T02:06:15.077+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-05T02:06:15.077+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-05T02:06:15.077+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-05T02:06:15.084+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): data_processing> on 2023-05-05 02:06:13.650215+00:00
[2023-05-05T02:06:15.088+0000] {standard_task_runner.py:55} INFO - Started process 107 to run task
[2023-05-05T02:06:15.089+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'stock_market_pipeline_v0', 'data_processing', 'manual__2023-05-05T02:06:13.650215+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmp7od9rhnx']
[2023-05-05T02:06:15.090+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask data_processing
[2023-05-05T02:06:15.123+0000] {task_command.py:389} INFO - Running <TaskInstance: stock_market_pipeline_v0.data_processing manual__2023-05-05T02:06:13.650215+00:00 [running]> on host eb70fa53aaaf
[2023-05-05T02:06:15.155+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kevin Freire
AIRFLOW_CTX_DAG_ID=stock_market_pipeline_v0
AIRFLOW_CTX_TASK_ID=data_processing
AIRFLOW_CTX_EXECUTION_DATE=2023-05-05T02:06:13.650215+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-05T02:06:13.650215+00:00
[2023-05-05T02:06:15.156+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-05T02:06:15.157+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/process_data.py']
[2023-05-05T02:06:15.165+0000] {subprocess.py:86} INFO - Output:
[2023-05-05T02:06:15.232+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/scripts/process_data.py': [Errno 2] No such file or directory
[2023-05-05T02:06:15.234+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-05-05T02:06:15.240+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-05-05T02:06:15.242+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=stock_market_pipeline_v0, task_id=data_processing, execution_date=20230505T020613, start_date=20230505T020615, end_date=20230505T020615
[2023-05-05T02:06:15.249+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 3 for task data_processing (Bash command failed. The command returned a non-zero exit code 2.; 107)
[2023-05-05T02:06:15.261+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-05T02:06:15.274+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
